# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-19 22:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='time_finished',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
